# Generated by Django 2.2.4 on 2019-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190806_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
