# Generated by Django 2.2.4 on 2019-08-28 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dad',
            field=models.ForeignKey(default=None, on_delete=False, related_name='DAD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mom',
            field=models.ForeignKey(default=None, on_delete=False, related_name='MOM', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.CharField(max_length=10),
        ),
    ]
