# Generated by Django 2.2.4 on 2019-08-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190828_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.RenameModel(
            old_name='Siblings',
            new_name='Sibling',
        ),
    ]
