# Generated by Django 2.2.4 on 2019-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dad',
            field=models.ForeignKey(default='', on_delete=False, related_name='DAD', to='home.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mom',
            field=models.ForeignKey(default='', on_delete=False, related_name='MOM', to='home.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(default='', on_delete=False, related_name='child', to='home.UserProfileInfo'),
        ),
    ]
