# Generated by Django 2.2.4 on 2019-08-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190828_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mom',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='DAD', to='home.UserProfileInfo'),
        ),
    ]
