# Generated by Django 2.2.4 on 2019-08-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190828_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DAD', to='home.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MOM', to='home.UserProfileInfo'),
        ),
    ]
