# Generated by Django 2.2.4 on 2019-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190828_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sibling',
            old_name='user',
            new_name='sibling1',
        ),
        migrations.RenameField(
            model_name='sibling',
            old_name='sibling',
            new_name='sibling2',
        ),
    ]
