# Generated by Django 2.2.4 on 2019-09-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190828_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='sex',
        ),
    ]
