# Generated by Django 2.2.4 on 2019-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_userprofileinfo_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
