# Generated by Django 2.2.4 on 2019-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MendelienGene',
            fields=[
                ('ensemblID', models.CharField(default='', max_length=300, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(default='', max_length=300)),
                ('sequence', models.TextField(max_length=2000000)),
                ('type', models.CharField(default='', max_length=300)),
                ('phenotype', models.CharField(default='', max_length=300)),
                ('chromosome', models.CharField(default='', max_length=30)),
                ('mim_entry_type', models.CharField(default='', max_length=300)),
                ('GeneSymbol', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
