# Generated by Django 2.2.4 on 2019-09-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MendelienDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mendeliengene',
            name='mim_entry_type',
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='GeneSymbol',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='sequence',
            field=models.TextField(default='', max_length=2000000),
        ),
    ]
