# Generated by Django 2.2.4 on 2019-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MendelienDatabase', '0002_auto_20190914_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='mendeliengene',
            name='reference',
            field=models.CharField(default='OMMIM', max_length=30),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='GeneSymbol',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='chromosome',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='ensemblID',
            field=models.CharField(blank=True, default='', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='gene_name',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='phenotype',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='sequence',
            field=models.TextField(blank=True, default='', max_length=2000000, null=True),
        ),
        migrations.AlterField(
            model_name='mendeliengene',
            name='type',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
