# Generated by Django 2.2.4 on 2019-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_x', models.FloatField(default=0, max_length=1)),
                ('user2_x', models.FloatField(default=0, max_length=1)),
                ('common', models.FloatField(default=0, max_length=1)),
                ('new', models.FloatField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='gene',
            fields=[
                ('NCIB_ID', models.CharField(default='', max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('genotype', models.FloatField(max_length=1)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='have',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='recombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibility', models.FloatField(max_length=1)),
                ('type', models.CharField(default='MAX', max_length=3)),
                ('label', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_possibility', models.FloatField(default=0, max_length=1)),
                ('max_possibility', models.FloatField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('test_type', models.CharField(max_length=100)),
                ('test_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('name', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('inheritance', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=100)),
                ('segment', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
