# Generated by Django 2.2.4 on 2019-08-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20190802_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='gene',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('genotype', models.FloatField(max_length=1)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('inheritance', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=100)),
                ('segment', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('e_mail', models.EmailField(default='', max_length=254)),
                ('profile_picture', models.CharField(default='', max_length=100000)),
                ('sex', models.BooleanField(default=True)),
                ('psw', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('date', models.DateField(auto_now=True)),
                ('test_type', models.CharField(max_length=100)),
                ('test_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to='home.UserProfileInfo')),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to='home.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_possibility', models.FloatField(default=0, max_length=1)),
                ('max_possibility', models.FloatField(default=1, max_length=1)),
                ('test_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.tests')),
            ],
        ),
        migrations.CreateModel(
            name='recombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibility', models.FloatField(max_length=1)),
                ('type', models.CharField(default='MAX', max_length=3)),
                ('label', models.CharField(default='', max_length=100)),
                ('test_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.tests')),
                ('user_gene', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.gene')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='have',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneTest.gene')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.UserProfileInfo')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='trait_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneTest.trait'),
        ),
        migrations.CreateModel(
            name='figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_x', models.FloatField(default=0, max_length=1)),
                ('user2_x', models.FloatField(default=0, max_length=1)),
                ('common', models.FloatField(default=0, max_length=1)),
                ('new', models.FloatField(default=0, max_length=1)),
                ('test_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.tests')),
            ],
        ),
    ]
