# Generated by Django 2.2.4 on 2019-08-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('GeneTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='user_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to='home.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='tests',
            name='user_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to='home.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='results',
            name='test_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.tests'),
        ),
        migrations.AddField(
            model_name='recombination',
            name='test_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.tests'),
        ),
        migrations.AddField(
            model_name='recombination',
            name='user_gene',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.gene'),
        ),
        migrations.AddField(
            model_name='recombination',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='have',
            name='gene_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneTest.gene'),
        ),
        migrations.AddField(
            model_name='have',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='gene',
            name='trait_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneTest.trait'),
        ),
        migrations.AddField(
            model_name='figure',
            name='test_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GeneTest.tests'),
        ),
    ]
