# Generated by Django 2.2.4 on 2019-08-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneTest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
