# Generated by Django 2.2.4 on 2019-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneTest', '0003_tests_accessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='IsXLinked',
            field=models.BooleanField(default=False),
        ),
    ]
