# Generated by Django 2.2.4 on 2019-09-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneTest', '0005_gene_is_genotype_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='is_genotype_set',
            new_name='IsGenotypeSet',
        ),
    ]
