# Generated by Django 2.2.4 on 2019-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneTest', '0006_auto_20190902_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='IsGenotypeSet',
        ),
        migrations.AddField(
            model_name='have',
            name='IsGenotypeSet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='have',
            name='genotype',
            field=models.FloatField(default=0, max_length=1),
        ),
    ]
