# Generated by Django 2.2.4 on 2019-09-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneTest', '0007_auto_20190910_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='MendelienGene',
            fields=[
                ('ensemblID', models.CharField(default='', max_length=300, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(default='', max_length=300)),
                ('sequence', models.TextField(default='', max_length=2000000)),
                ('type', models.CharField(default='', max_length=300)),
                ('phenotype', models.CharField(default='', max_length=300)),
                ('chromosome', models.CharField(default='', max_length=30)),
                ('GeneSymbol', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
