# Generated by Django 2.2.4 on 2019-09-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneTest', '0008_mendeliengene'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MendelienGene',
        ),
    ]
